### ISSUE TITLE
希望请教一下弹窗的实现方法，感谢

### ISSUE THREAD

**Issue by jiangotto** [Vainlory/mypaint#1]
from a ZJUer

**Comment by N7Utb** [comment]
弹窗是小白上学期汇编课讲过得windows.h中得messagebox函数，可以实现弹窗。另外能请教下您是怎么保存和读取得文件得时候是会卡死得，是否是按我最近更新得readme中得方法来保存和读取的。谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"蒋宇涵"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月3日(星期三) 晚上8:30
收件人:&nbsp;"Vainlory/mypaint"<mypaint@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[Vainlory/mypaint] 希望请教一下弹窗的实现方法，感谢 (#1)





 
from a ZJUer

**Comment by jiangotto** [comment]
好的，非常感谢。还有一个问题想要请教，就是我在运行程序的时候，不论是鼠标移动还是点击屏幕上的内容都会时不时地闪烁两下，不知道你们是否有遇到这个问题，或者说知道该如何避免吗。非常感谢。

**Comment by N7Utb** [comment]
emmmm这个问题我们没有遇到，不过我印象中应该 是那个定时器回调函数没开是一个可能得原因，这个应该是个屏闪得问题，可能与图形库本身有关。（您还是没有说您是怎么卡死得233333，望告知




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "蒋宇涵"<notifications@github.com&gt;; 
发送时间: 2020年6月3日(星期三) 晚上10:10
收件人: "Vainlory/mypaint"<mypaint@noreply.github.com&gt;; 
抄送: "765228482"<765228482@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Vainlory/mypaint] 希望请教一下弹窗的实现方法，感谢 (#1)





 
好的，非常感谢。还有一个问题想要请教，就是我在运行程序的时候，不论是鼠标移动还是点击屏幕上的内容都会时不时地闪烁两下，不知道你们是否有遇到这个问题，或者说知道该如何避免吗。非常感谢。

**Comment by jiangotto** [comment]
因为我现在不在家，忘了刚刚是怎么保存和读取操作的，等会儿回家再试一下

**Comment by jiangotto** [comment]
ok,已解决，保存时未手动将文件后缀名.txt加上
